server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICES
          uri: lb://USER-SERVICES
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICES
          uri: lb://HOTEL-SERVICES
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICES
          uri: lb://RATING-SERVICES
          predicates:
            - Path=/ratings/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8760/eureka


#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-57577705.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaadc6kly2faQlDj5d7
    client-secret: J702z5kjoPF0bqkAcPsWQGljbhq_MgzT60lvsos8
    scopes: openid, profile, email, offline_access